import archiver from 'archiver';
import { Response } from 'express';
import { PlatformProject } from './platform-project.model';

type GeneratedFile = { path: string; content: string; language?: string };

function normalizeFiles(files: GeneratedFile[]) {
  return (Array.isArray(files) ? files : [])
    .filter((file: any) => file && typeof file.path === 'string')
    .map((file: any) => {
      const rawContent = file.content;
      let content: string;

      if (typeof rawContent === 'string') {
        content = rawContent;
      } else {
        try {
          content = JSON.stringify(rawContent, null, 2);
        } catch {
          content = String(rawContent ?? '');
        }
      }

      return {
        path: String(file.path),
        content,
        language: typeof file.language === 'string' ? file.language : undefined
      };
    });
}

export class PlatformProjectsService {
  async createProject(
    userId: string,
    data: {
      name: string;
      modules: string[];
      template: string;
      backend: string;
      provider: string;
      designSeed?: string;
      description?: string;
    }
  ) {
    return PlatformProject.create({ userId, ...data, status: 'generating' });
  }

  async saveFiles(projectId: string, files: GeneratedFile[]) {
    const normalizedFiles = normalizeFiles(files);

    return PlatformProject.findByIdAndUpdate(
      projectId,
      { files: normalizedFiles, fileCount: normalizedFiles.length, status: 'complete' },
      { new: true }
    );
  }

  async appendChatEntry(
    projectId: string,
    userId: string,
    entry: { type: 'generate' | 'refine'; prompt: string }
  ) {
    return PlatformProject.findOneAndUpdate(
      { _id: projectId, userId },
      {
        $push: {
          chatHistory: {
            type: entry.type,
            prompt: entry.prompt,
            createdAt: new Date()
          }
        }
      },
      { new: true }
    );
  }

  async listUserProjects(userId: string) {
    return PlatformProject.find({ userId })
      .select(
        'name modules template backend status fileCount createdAt updatedAt vercelDeployUrl githubRepoUrl railwayServiceUrl'
      )
      .sort({ updatedAt: -1 })
      .limit(50);
  }

  async getProject(projectId: string, userId: string) {
    const project = await PlatformProject.findOne({ _id: projectId, userId });
    if (!project) {
      throw new Error('Project not found');
    }
    return project;
  }

  async deleteProject(projectId: string, userId: string) {
    const result = await PlatformProject.deleteOne({ _id: projectId, userId });
    if (result.deletedCount === 0) {
      throw new Error('Project not found');
    }
  }

  async streamZipDownload(projectId: string, userId: string, res: Response) {
    const project = await this.getProject(projectId, userId);

    res.setHeader('Content-Type', 'application/zip');
    res.setHeader('Content-Disposition', `attachment; filename="${project.name}.zip"`);

    const archive = archiver('zip', { zlib: { level: 9 } });
    archive.pipe(res);

    for (const file of project.files as GeneratedFile[]) {
      archive.append(file.content, { name: file.path });
    }

    archive.append(this.buildReadme(project), { name: 'SETUP.md' });
    await archive.finalize();
  }

  private buildReadme(project: any): string {
    return `# ${project.name}

Generated by IDEA Platform on ${new Date(project.createdAt).toLocaleDateString()}

## Stack
- Template: ${project.template}
- Backend: ${project.backend}
- Modules: ${project.modules.join(', ')}

## Setup

\`\`\`bash
# Backend
cd backend
npm install
cp .env.example .env
# Edit .env and set DATABASE_URL, JWT_SECRET
npm run dev

# Frontend
cd frontend
npm install
cp .env.example .env.local
npm run dev
\`\`\`

## Access
- Frontend: http://localhost:3000
- Backend: http://localhost:5000
`;
  }
}

export const platformProjectsService = new PlatformProjectsService();
